version: '3.1'

services:
  db:
    image: mysql:8.2.0
    environment:
      MYSQL_DATABASE: 'sample'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"